GET http://localhost:3000/contact
###
POST http://localhost:3000/contact
Content-Type: application/json

{
    "name":"Marcell",
    "phone":"123123",
    "isActive": "true"
}
###
PUT http://localhost:3000/contact/79f99cd1-9982-4f2f-bfb4-710119f27a3a
Content-Type: application/json

{
    "name":"Reis",
    "phone":"12vchjdbs",
    "isActive": "true"
}
###
PATCH http://localhost:3000/contact/8251c1f0-3035-4927-b7f4-68b148a2fc20
Content-Type: application/json

{
    "name": "Fernanda Reis",
   "phone":"12vchjdbs"
}
###
DELETE http://localhost:3000/contact/0666f6aa-54c7-4b61-8b1e-e69b4ce1aa0f
