GET http://localhost:3000/contact
###
POST http://localhost:3000/contact
Content-Type: application/json

{
    "name":"Marcell",
    "phone":"123123",
    "isActive": "true"
}
###

PUT http://localhost:3000/contact/d16a1f13-7436-4e73-a339-abadafd74190
Content-Type: application/json

{
    "name":"Reis",
    "phone":"12vchjdbs",
    "isActive": "true"
}
###
PATCH http://localhost:3000/contact/e8ffaa7b-8476-4b7a-9927-e58ff58e98ea
Content-Type: application/json

{
    "name": "Fernanda Reis",
   "phone":"12vchjdbs"
}
###
DELETE http://localhost:3000/contact/0666f6aa-54c7-4b61-8b1e-e69b4ce1aa0f